### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ufofmt#12]

**Comment by chrissimpkins** [comment]
Pushed v0.3.0 as first crates.io release and added user rustdoc documentation + README.md repository documentation

**Comment by chrissimpkins** [comment]
@madig tried to add you as an owner on crates.io but I get the following error:

```
error: failed to invite owners to crate `ufofmt` on registry at https://crates.io

Caused by:
  the remote server responded with an error: could not find user with login `madig`
```

Do you have a crates.io account set up?

**Comment by madig** [comment]
Nope, I got nothing. Will do one day maybe.

**Comment by chrissimpkins** [comment]
I think that it only requires you to link your GH account.  crates.io works off of GH id's.
