### ISSUE TITLE
Serialize consistent cross-platform line endings across plist, glif, and feature files

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ufofmt#32]
Support line feed line endings as the cross-platform default across glif, plist, and fea files.

Requires https://github.com/linebender/norad/pull/172 changes in norad

**Comment by chrissimpkins** [comment]
@cmyr Colin, is there a chance that we can cut a new norad release with the https://github.com/linebender/norad/pull/172 changes?  I'd like to get to a stable default serialization format and then share this tool out to a few UFO based development  teams/UFO spec stakeholders for feedback.  Absolutely no rush.

**Comment by cmyr** [comment]
I've published `0.5.1` to crates.io

**Comment by chrissimpkins** [comment]
Thank you very much Colin!

**Comment by chrissimpkins** [comment]
https://github.com/source-foundry/ufofmt/pull/33
